"""Add Validation field to Clientkey

Revision ID: 5fb20d95982a
Revises: b5daa480f480
Create Date: 2024-08-04 08:32:58.798162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb20d95982a'
down_revision: Union[str, None] = 'b5daa480f480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_keys', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.add_column('client_keys', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_keys', 'last_updated')
    op.drop_column('client_keys', 'is_valid')
    # ### end Alembic commands ###
