"""Made Traffic Signal Coords unique

Revision ID: a32f9b2fe525
Revises: a526efba7221
Create Date: 2024-07-28 20:32:49.791817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32f9b2fe525'
down_revision: Union[str, None] = 'a526efba7221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_latitude_longitude', 'traffic_signals', ['latitude', 'longitude'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_latitude_longitude', 'traffic_signals', type_='unique')
    # ### end Alembic commands ###
