"""Add Clientkey for encyption

Revision ID: b5daa480f480
Revises: a32f9b2fe525
Create Date: 2024-08-04 08:31:16.584608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5daa480f480'
down_revision: Union[str, None] = 'a32f9b2fe525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_keys',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('shared_key', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_client_keys_client_id'), 'client_keys', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_keys_client_id'), table_name='client_keys')
    op.drop_table('client_keys')
    # ### end Alembic commands ###
