"""Initial migration

Revision ID: c3a8b86b2179
Revises: 
Create Date: 2024-07-26 20:02:39.213694

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3a8b86b2179'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_signal_status',
                    sa.Column('signal_id', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('time_from_last_change', sa.DateTime(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('signal_id')
                    )
    op.create_index(op.f('ix_traffic_signal_status_signal_id'), 'traffic_signal_status', ['signal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_signal_status_signal_id'), table_name='traffic_signal_status')
    op.drop_table('traffic_signal_status')
    # ### end Alembic commands ###
